allowBuilds:
  "@prisma/engines": true
  "@sentry/cli": true
  esbuild: true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - "@sentry/cli"
  - esbuild
  - prisma
  - unrs-resolver
